// Generated by LiveScript 1.2.0
(function(){
  define(['items/item', './dummyText', './dummyUsers', 'underscore', 'util'], function(its, duT, dU, _, util){
    var dummyUsers, userNum, dummyItems;
    dummyUsers = _.chain(dU).pluck('user').shuffle().value();
    userNum = _(dummyUsers).size();
    dummyItems = _(duT).map(function(it){
      return its.newItem(it, dummyUsers[util.random(userNum)].sha1_hash);
    });
    return {
      status: function(){
        return {
          items: 983,
          meta: 307,
          keys: 125
        };
      },
      items: function(){
        return dummyItems;
      },
      me: function(){
        return dummyUsers[0];
      },
      friends: function(){
        return dummyUsers;
      },
      item: function(id){
        return _(dummyItems).find(function(it){
          return it.id === id;
        });
      },
      friend: function(id){
        return _(dummyUsers).find(function(it){
          return it.sha1_hash === id;
        });
      }
    };
  });
}).call(this);
