// Generated by LiveScript 1.2.0
(function(){
  var express, app, db;
  express = require('express');
  app = express();
  db = require('./db.js');
  app.get('/', function(req, res){
    return db.items(function(err, data){
      res.type('text/json');
      return res.send(data);
    });
  });
  app.listen(process.env.PORT || 4730);
}).call(this);
