// Generated by LiveScript 1.2.0
(function(){
  var restler, re, restler1, re1;
  restler = require('restler');
  re = restler.get('http://localhost:4731/users/id');
  console.log("re create here");
  re.on('success', function(data, res){
    return console.log('re on success');
  });
  restler1 = require('restler');
  re1 = restler1.get('http://localhost:4731/users');
  console.log("re1 create here");
  re1.on('success', function(data, res){
    return console.log('re1 on success');
  });
}).call(this);
