// Generated by LiveScript 1.2.0
(function(){
  var express, _, app, db;
  express = require('express');
  _ = require('underscore');
  app = express();
  app.use(express.bodyParser());
  db = require('./db.js');
  app.get('/items', function(req, res){
    return db.items.find({}, function(err, data){
      res.type('text/json');
      return res.send(data);
    });
  });
  app.get('/items/idv', function(req, res){
    return db.items.find({}, function(err, data){
      res.type('text/json');
      return res.send(_(data).map(function(it){
        return [it.id, it.version.name];
      }));
    });
  });
  app.get('/users', function(req, res){
    var q;
    q = typeof req.query === 'function' ? req.query({}) : void 8;
    return db.users.find(q, function(err, data){
      res.type('text/json');
      return res.send(data);
    });
  });
  app.get('/users/idv', function(req, res){
    return db.users.find({}, function(err, data){
      res.type('text/json');
      return res.send(_(data).map(function(it){
        return [it.id, it.version.name];
      }));
    });
  });
  app.post('/items', function(req, res){
    var item;
    item = req.body;
    return db.items.insert(item, function(){
      return res.status(201).send(item.id);
    });
  });
  app.post('/users', function(req, res){
    var user;
    user = req.body;
    console.log(user);
    return db.users.insert(user, function(){
      return res.status(201).send(user.id);
    });
  });
  app.listen(process.env.PORT || 4731);
}).call(this);
