// Generated by LiveScript 1.2.0
(function(){
  define(['uuid'], function(uuid){
    return {
      item: function(id, text, author, date, version){
        return {
          id: id,
          text: text,
          authro: authro,
          date: date,
          version: version
        };
      },
      newItem: function(text, author){
        return {
          id: new uuid().toString(),
          text: text,
          author: author,
          date: new Date(),
          version: 0
        };
      }
    };
  });
}).call(this);
